services:
  gluetun:
    image: ghcr.io/qdm12/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - SERVER_CITIES=${SERVER_CITIES}
      - VPN_PORT_FORWARDING=on
      - TZ=${TZ}
      - QBT_WEBUI_ENABLED=true
    volumes:
      - /mnt/nas/services/qbittorrent/config/config.toml:/gluetun/auth/config.toml
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://google.com"]
      interval: 30s
      timeout: 10s
      retries: 3

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - QBITTORRENT_INTERFACE=tun0
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
      - DOCKER_MODS=ghcr.io/t-anc/gsp-qbittorent-gluetun-sync-port-mod:main
      - GSP_GTN_API_KEY=${GSP_GTN_API_KEY:-randomapikey}
      - GSP_QBITTORRENT_PORT=${GSP_QBITTORRENT_PORT:-53764}
      - GSP_MINIMAL_LOGS=false
    volumes:
      - /mnt/nas/services/qbittorrent/config:/config
      - /mnt/nas/services/qbittorrent/vuetorrent:/vuetorrent
      - /mnt/nas/services/qbittorrent/incomplete:/incomplete
      - /mnt/nas/services/qbittorrent/complete:/downloads
      - /mnt/nas/books/audiobooks:/audiobooks
    ulimits:
      nofile:
        soft: 32768
        hard: 65536
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v2/app/version"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  cross-seed:
    image: ghcr.io/cross-seed/cross-seed:6
    container_name: cross-seed
    ports:
      - "2468:2468"
    volumes:
      - /mnt/nas/services/qbittorrent/complete:/downloads
      - /mnt/nas/services/qbittorrent/cross-seed-config:/config
    command: daemon
    restart: unless-stopped
    depends_on:
      qbittorrent:
        condition: service_healthy
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - DOWNLOAD_DIR=/downloads
      - LINK_DIR=/downloads/linked

volumes:
  qbittorrent-config:
